name: Deploy

inputs:
  # SSH
  host:
    required: true
  username:
    required: true
  port:
    required: true
  ssh-private-key:
    required: true

  # Docker
  image-name:
    required: true
  server-port:
    required: true
  container-name:
    required: true
  application-port:
    required: true

  # App
  swagger-username:
    required: true
  swagger-password:
    required: true
  mongo-url:
    required: true
  jwt-secret:
    required: true
  dev-auth-password:
    required: true

runs:
  using: "composite"
  steps:
    - name: Update image inside VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}
        PORT: ${{ inputs.port }}
        KEY: ${{ inputs.ssh-private-key }}
        script: |
          docker pull ${{ inputs.image-name }}
          docker rm -f ${{ inputs.container-name }}
          docker run -d \
          -p ${{ inputs.server-port }}:${{ inputs.application-port }} \
          --restart=always \
          --add-host=host.docker.internal:host-gateway \
          --name ${{ inputs.container-name }} \
          -e SWAGGER_USERNAME=${{ inputs.swagger-username }} \
          -e SWAGGER_PASSWORD=${{ inputs.swagger-password }} \
          -e MONGO_URL=${{ inputs.mongo-url }} \
          -e JWT_SECRET=${{ inputs.jwt-secret }} \
          -e DEV_AUTH_PASSWORD=${{ inputs.dev-auth-password }} \
          -e IS_DEV_ENV=${{ inputs.is-dev-environment }} \
          -e PORT=${{ inputs.application-port }} \
          -e LOGDASH_API_KEY=${{ inputs.logdash-api-key }} \
          ${{ inputs.image-name }}
