name: Execute e2e tests (backend)

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run e2e tests
        run: yarn test:e2e
